//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        internal static string bienvenido {
            get {
                return ResourceManager.GetString("bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejecución abortada..
        /// </summary>
        internal static string ejec_abort {
            get {
                return ResourceManager.GetString("ejec_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al ejecutar la acción, refresque e intente de nuevo..
        /// </summary>
        internal static string error_accion {
            get {
                return ResourceManager.GetString("error_accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, ya exite un registro con el mismo código..
        /// </summary>
        internal static string error_cod_igual {
            get {
                return ResourceManager.GetString("error_cod_igual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, registro ya existente.
        /// </summary>
        internal static string error_exist {
            get {
                return ResourceManager.GetString("error_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener la respuesta del procedimiento..
        /// </summary>
        internal static string error_get_proc {
            get {
                return ResourceManager.GetString("error_get_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al guardar el registro..
        /// </summary>
        internal static string error_guardar {
            get {
                return ResourceManager.GetString("error_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas al inicializar el horario..
        /// </summary>
        internal static string error_inicializar_horario {
            get {
                return ResourceManager.GetString("error_inicializar_horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar editar un registro..
        /// </summary>
        internal static string error_intento_editar {
            get {
                return ResourceManager.GetString("error_intento_editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error intentando guardar el registro..
        /// </summary>
        internal static string error_intento_guardar {
            get {
                return ResourceManager.GetString("error_intento_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error interno. .
        /// </summary>
        internal static string error_interno {
            get {
                return ResourceManager.GetString("error_interno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al leer la respuesta del proceso..
        /// </summary>
        internal static string error_leer_proc {
            get {
                return ResourceManager.GetString("error_leer_proc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al mostrar los registros..
        /// </summary>
        internal static string error_llenar_registros {
            get {
                return ResourceManager.GetString("error_llenar_registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complicaciones con el inicio de sesión. Consulte con soporte si el problema contiúa..
        /// </summary>
        internal static string error_loggin {
            get {
                return ResourceManager.GetString("error_loggin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario o contraseña incorrectos..
        /// </summary>
        internal static string error_loggin_credenciales {
            get {
                return ResourceManager.GetString("error_loggin_credenciales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cuenta con los permisos para ingresar..
        /// </summary>
        internal static string error_loggin_unauthorized {
            get {
                return ResourceManager.GetString("error_loggin_unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al mostrar el registro a editar..
        /// </summary>
        internal static string error_mostrar_reg_edit {
            get {
                return ResourceManager.GetString("error_mostrar_reg_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, no existe el registro a actualizar..
        /// </summary>
        internal static string error_no_existe {
            get {
                return ResourceManager.GetString("error_no_existe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, no se pudo obtener el registro..
        /// </summary>
        internal static string error_obt_reg {
            get {
                return ResourceManager.GetString("error_obt_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, no se pudo obtener los registros..
        /// </summary>
        internal static string error_obt_regs {
            get {
                return ResourceManager.GetString("error_obt_regs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al obtener el registro a guardar. Refresque e intente de nuevo..
        /// </summary>
        internal static string error_obt_reg_a_guardar {
            get {
                return ResourceManager.GetString("error_obt_reg_a_guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, registro no actualizado..
        /// </summary>
        internal static string error_reg_actualizado {
            get {
                return ResourceManager.GetString("error_reg_actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro a editar inválido..
        /// </summary>
        internal static string error_reg_edit_inval {
            get {
                return ResourceManager.GetString("error_reg_edit_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, registro no insertado..
        /// </summary>
        internal static string error_reg_insertado {
            get {
                return ResourceManager.GetString("error_reg_insertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error, ya existe otro registro con alguno de los datos del registro a guardar..
        /// </summary>
        internal static string error_sql_2627 {
            get {
                return ResourceManager.GetString("error_sql_2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error con algunos de los datos del registro a guardar..
        /// </summary>
        internal static string error_sql_515 {
            get {
                return ResourceManager.GetString("error_sql_515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de descuento inválido..
        /// </summary>
        internal static string error_tipo_desc_inval {
            get {
                return ResourceManager.GetString("error_tipo_desc_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string error_w_status {
            get {
                return ResourceManager.GetString("error_w_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos se limpiarán!.
        /// </summary>
        internal static string msj_campos_limpiar {
            get {
                return ResourceManager.GetString("msj_campos_limpiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Continuar?.
        /// </summary>
        internal static string msj_continuar {
            get {
                return ResourceManager.GetString("msj_continuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de registros vacía..
        /// </summary>
        internal static string msj_lista_vacia {
            get {
                return ResourceManager.GetString("msj_lista_vacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro actualizado..
        /// </summary>
        internal static string succ_actualizado {
            get {
                return ResourceManager.GetString("succ_actualizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro insertado..
        /// </summary>
        internal static string succ_insertado {
            get {
                return ResourceManager.GetString("succ_insertado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay campos requeridos que están incompletos..
        /// </summary>
        internal static string validacion_campos_requeridos {
            get {
                return ResourceManager.GetString("validacion_campos_requeridos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta información requerida..
        /// </summary>
        internal static string validacion_campos_vacios {
            get {
                return ResourceManager.GetString("validacion_campos_vacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad debe ser mayor a 0..
        /// </summary>
        internal static string validacion_cant_may_0 {
            get {
                return ResourceManager.GetString("validacion_cant_may_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La categoría es requerida..
        /// </summary>
        internal static string validacion_categ_req {
            get {
                return ResourceManager.GetString("validacion_categ_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código debe ser a lo sumo de {0} caracteres..
        /// </summary>
        internal static string validacion_cod_max {
            get {
                return ResourceManager.GetString("validacion_cod_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código es requerido..
        /// </summary>
        internal static string validacion_cod_req {
            get {
                return ResourceManager.GetString("validacion_cod_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El departamento es requerido..
        /// </summary>
        internal static string validacion_depart_req {
            get {
                return ResourceManager.GetString("validacion_depart_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción debe ser a lo sumo de {0} caracteres..
        /// </summary>
        internal static string validacion_desc_maxLen {
            get {
                return ResourceManager.GetString("validacion_desc_maxLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción es requerida..
        /// </summary>
        internal static string validacion_desc_req {
            get {
                return ResourceManager.GetString("validacion_desc_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha inválida..
        /// </summary>
        internal static string validacion_fecha {
            get {
                return ResourceManager.GetString("validacion_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forma de rebajo requerido.
        /// </summary>
        internal static string validacion_forma_req {
            get {
                return ResourceManager.GetString("validacion_forma_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un valor..
        /// </summary>
        internal static string validacion_ing_valor {
            get {
                return ResourceManager.GetString("validacion_ing_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor inválido..
        /// </summary>
        internal static string validacion_invalid {
            get {
                return ResourceManager.GetString("validacion_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El límite de edad no puede ser mayor a {0}..
        /// </summary>
        internal static string validacion_limEdad_max {
            get {
                return ResourceManager.GetString("validacion_limEdad_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El límite de edad debe ser mayor o igual a {0}..
        /// </summary>
        internal static string validacion_limEdad_min {
            get {
                return ResourceManager.GetString("validacion_limEdad_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El límite de edad es requerido..
        /// </summary>
        internal static string validacion_limEdad_req {
            get {
                return ResourceManager.GetString("validacion_limEdad_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar a lo sumo {0} caracteres..
        /// </summary>
        internal static string validacion_max {
            get {
                return ResourceManager.GetString("validacion_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje debe ser a lo sumo de {0} caracteres..
        /// </summary>
        internal static string validacion_msj_max {
            get {
                return ResourceManager.GetString("validacion_msj_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El mensaje es requerido..
        /// </summary>
        internal static string validacion_msj_req {
            get {
                return ResourceManager.GetString("validacion_msj_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre debe ser a lo sumo de {0} caracteres..
        /// </summary>
        internal static string validacion_nom_max {
            get {
                return ResourceManager.GetString("validacion_nom_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido..
        /// </summary>
        internal static string validacion_nom_req {
            get {
                return ResourceManager.GetString("validacion_nom_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor numérico inválido..
        /// </summary>
        internal static string validacion_num_inval {
            get {
                return ResourceManager.GetString("validacion_num_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo es requerido..
        /// </summary>
        internal static string validacion_req {
            get {
                return ResourceManager.GetString("validacion_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incremento de tiempo inválido..
        /// </summary>
        internal static string validacion_time_sche_inval {
            get {
                return ResourceManager.GetString("validacion_time_sche_inval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El incremento de tiempo es requerido..
        /// </summary>
        internal static string validacion_time_sche_req {
            get {
                return ResourceManager.GetString("validacion_time_sche_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de descuento es requerido..
        /// </summary>
        internal static string validacion_tipoDesc_req {
            get {
                return ResourceManager.GetString("validacion_tipoDesc_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El título debe ser a lo sumo de {0} caracteres..
        /// </summary>
        internal static string validacion_titulo_max {
            get {
                return ResourceManager.GetString("validacion_titulo_max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El título es requerido..
        /// </summary>
        internal static string validacion_titulo_req {
            get {
                return ResourceManager.GetString("validacion_titulo_req", resourceCulture);
            }
        }
    }
}
