//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class views {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal views() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.views", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acción.
        /// </summary>
        internal static string accion {
            get {
                return ResourceManager.GetString("accion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo de Cuentas.
        /// </summary>
        internal static string accountgroup {
            get {
                return ResourceManager.GetString("accountgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        internal static string activo {
            get {
                return ResourceManager.GetString("activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string agregar {
            get {
                return ResourceManager.GetString("agregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Nuevo Término de Pago.
        /// </summary>
        internal static string agregarTermPag {
            get {
                return ResourceManager.GetString("agregarTermPag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Año.
        /// </summary>
        internal static string ano {
            get {
                return ResourceManager.GetString("ano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        internal static string apeCliente {
            get {
                return ResourceManager.GetString("apeCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aprobar.
        /// </summary>
        internal static string aprobar {
            get {
                return ResourceManager.GetString("aprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículo.
        /// </summary>
        internal static string articulo {
            get {
                return ResourceManager.GetString("articulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artículos.
        /// </summary>
        internal static string articulos {
            get {
                return ResourceManager.GetString("articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignar Espacios Fríos.
        /// </summary>
        internal static string asig_frios {
            get {
                return ResourceManager.GetString("asig_frios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asignación de Proveedor.
        /// </summary>
        internal static string asig_prov {
            get {
                return ResourceManager.GetString("asig_prov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance de Cierre.
        /// </summary>
        internal static string balcierrcuenta {
            get {
                return ResourceManager.GetString("balcierrcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance de Cliente.
        /// </summary>
        internal static string balClien {
            get {
                return ResourceManager.GetString("balClien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string balcuenta {
            get {
                return ResourceManager.GetString("balcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        internal static string buscar {
            get {
                return ResourceManager.GetString("buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabeceras.
        /// </summary>
        internal static string cabecera {
            get {
                return ResourceManager.GetString("cabecera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camara.
        /// </summary>
        internal static string camara {
            get {
                return ResourceManager.GetString("camara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad.
        /// </summary>
        internal static string cant {
            get {
                return ResourceManager.GetString("cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad a Obtener con descuento.
        /// </summary>
        internal static string cant_desc {
            get {
                return ResourceManager.GetString("cant_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad a Comprar a precio completo.
        /// </summary>
        internal static string cant_prec {
            get {
                return ResourceManager.GetString("cant_prec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargando....
        /// </summary>
        internal static string cargando {
            get {
                return ResourceManager.GetString("cargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo Finaciero.
        /// </summary>
        internal static string cargoFi {
            get {
                return ResourceManager.GetString("cargoFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargos.
        /// </summary>
        internal static string cargos {
            get {
                return ResourceManager.GetString("cargos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoría.
        /// </summary>
        internal static string categ {
            get {
                return ResourceManager.GetString("categ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorías.
        /// </summary>
        internal static string categs {
            get {
                return ResourceManager.GetString("categs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar.
        /// </summary>
        internal static string cerrar {
            get {
                return ResourceManager.GetString("cerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciudad.
        /// </summary>
        internal static string ciudad {
            get {
                return ResourceManager.GetString("ciudad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clientes.
        /// </summary>
        internal static string clientes {
            get {
                return ResourceManager.GetString("clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cobros.
        /// </summary>
        internal static string cobros {
            get {
                return ResourceManager.GetString("cobros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string cod {
            get {
                return ResourceManager.GetString("cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Códigos de razón.
        /// </summary>
        internal static string cods_razon {
            get {
                return ResourceManager.GetString("cods_razon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad de columnas.
        /// </summary>
        internal static string column_visib {
            get {
                return ResourceManager.GetString("column_visib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones Comercial.
        /// </summary>
        internal static string comercial {
            get {
                return ResourceManager.GetString("comercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comercialización.
        /// </summary>
        internal static string comercio {
            get {
                return ResourceManager.GetString("comercio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compradores.
        /// </summary>
        internal static string compradores {
            get {
                return ResourceManager.GetString("compradores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compras.
        /// </summary>
        internal static string compras {
            get {
                return ResourceManager.GetString("compras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condiciones de pago.
        /// </summary>
        internal static string conds_pago {
            get {
                return ResourceManager.GetString("conds_pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuración.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contratos.
        /// </summary>
        internal static string contratos {
            get {
                return ResourceManager.GetString("contratos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string copiar {
            get {
                return ResourceManager.GetString("copiar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuenta de Facturación.
        /// </summary>
        internal static string cuenFac {
            get {
                return ResourceManager.GetString("cuenFac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear Cuenta a Crédito.
        /// </summary>
        internal static string cuentaACredito {
            get {
                return ResourceManager.GetString("cuentaACredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuentas.
        /// </summary>
        internal static string cuentas {
            get {
                return ResourceManager.GetString("cuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Adicional 1.
        /// </summary>
        internal static string customdate1 {
            get {
                return ResourceManager.GetString("customdate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Adicional 2.
        /// </summary>
        internal static string customdate2 {
            get {
                return ResourceManager.GetString("customdate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Adicional 3.
        /// </summary>
        internal static string customdate3 {
            get {
                return ResourceManager.GetString("customdate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Adicional 4.
        /// </summary>
        internal static string customdate4 {
            get {
                return ResourceManager.GetString("customdate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Adicional 5.
        /// </summary>
        internal static string customdate5 {
            get {
                return ResourceManager.GetString("customdate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente es Empleado.
        /// </summary>
        internal static string customerisemployee {
            get {
                return ResourceManager.GetString("customerisemployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Adicional 1.
        /// </summary>
        internal static string customnum1 {
            get {
                return ResourceManager.GetString("customnum1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Adicional 2.
        /// </summary>
        internal static string customnum2 {
            get {
                return ResourceManager.GetString("customnum2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Adicional 3.
        /// </summary>
        internal static string customnum3 {
            get {
                return ResourceManager.GetString("customnum3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Adicional 4.
        /// </summary>
        internal static string customnum4 {
            get {
                return ResourceManager.GetString("customnum4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono Adicional 5.
        /// </summary>
        internal static string customnum5 {
            get {
                return ResourceManager.GetString("customnum5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Adicional 1.
        /// </summary>
        internal static string customtext1 {
            get {
                return ResourceManager.GetString("customtext1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Adicional 2.
        /// </summary>
        internal static string customtext2 {
            get {
                return ResourceManager.GetString("customtext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Adicional 3.
        /// </summary>
        internal static string customtext3 {
            get {
                return ResourceManager.GetString("customtext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto Adicional 4.
        /// </summary>
        internal static string customtext4 {
            get {
                return ResourceManager.GetString("customtext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos del Proveedor.
        /// </summary>
        internal static string datos_prov {
            get {
                return ResourceManager.GetString("datos_prov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        internal static string depart {
            get {
                return ResourceManager.GetString("depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamentos.
        /// </summary>
        internal static string departs {
            get {
                return ResourceManager.GetString("departs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desaprobar.
        /// </summary>
        internal static string desaprobar {
            get {
                return ResourceManager.GetString("desaprobar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descontar artículos impares.
        /// </summary>
        internal static string descont_impares {
            get {
                return ResourceManager.GetString("descont_impares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string descripcion {
            get {
                return ResourceManager.GetString("descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuento.
        /// </summary>
        internal static string descuento {
            get {
                return ResourceManager.GetString("descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descuentos.
        /// </summary>
        internal static string descuentos {
            get {
                return ResourceManager.GetString("descuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalle.
        /// </summary>
        internal static string detalle {
            get {
                return ResourceManager.GetString("detalle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinámica.
        /// </summary>
        internal static string dinamica {
            get {
                return ResourceManager.GetString("dinamica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        internal static string domingo {
            get {
                return ResourceManager.GetString("domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiada 1 fila al portapapeles.
        /// </summary>
        internal static string dtable_copy1 {
            get {
                return ResourceManager.GetString("dtable_copy1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiadas %d filas al portapapeles.
        /// </summary>
        internal static string dtable_copyMore {
            get {
                return ResourceManager.GetString("dtable_copyMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar al portapapeles.
        /// </summary>
        internal static string dtable_copyTitle {
            get {
                return ResourceManager.GetString("dtable_copyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primera.
        /// </summary>
        internal static string dtable_first {
            get {
                return ResourceManager.GetString("dtable_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _TOTAL_ registro(s) encontrado(s).
        /// </summary>
        internal static string dtable_info {
            get {
                return ResourceManager.GetString("dtable_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún registro disponible..
        /// </summary>
        internal static string dtable_infoEmpty {
            get {
                return ResourceManager.GetString("dtable_infoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Filtrado de _MAX_ registros totales)..
        /// </summary>
        internal static string dtable_infoFiltered {
            get {
                return ResourceManager.GetString("dtable_infoFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última.
        /// </summary>
        internal static string dtable_last {
            get {
                return ResourceManager.GetString("dtable_last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar _MENU_ registros por página.
        /// </summary>
        internal static string dtable_lengthMenu {
            get {
                return ResourceManager.GetString("dtable_lengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previa.
        /// </summary>
        internal static string dtable_previa {
            get {
                return ResourceManager.GetString("dtable_previa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siguiente.
        /// </summary>
        internal static string dtable_sig {
            get {
                return ResourceManager.GetString("dtable_sig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ningún registro..
        /// </summary>
        internal static string dtable_zeroRecords {
            get {
                return ResourceManager.GetString("dtable_zeroRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Término de Pago.
        /// </summary>
        internal static string editTermpag {
            get {
                return ResourceManager.GetString("editTermpag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electricidad.
        /// </summary>
        internal static string electricidad {
            get {
                return ResourceManager.GetString("electricidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección de Correo Electrónico.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compañía.
        /// </summary>
        internal static string empCliente {
            get {
                return ResourceManager.GetString("empCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrega.
        /// </summary>
        internal static string entrega {
            get {
                return ResourceManager.GetString("entrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacios.
        /// </summary>
        internal static string espacios {
            get {
                return ResourceManager.GetString("espacios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacios Frios.
        /// </summary>
        internal static string espacio_frio {
            get {
                return ResourceManager.GetString("espacio_frio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        internal static string estadoCliente {
            get {
                return ResourceManager.GetString("estadoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente está excento de impuestos.
        /// </summary>
        internal static string exempttax {
            get {
                return ResourceManager.GetString("exempttax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familia.
        /// </summary>
        internal static string familia {
            get {
                return ResourceManager.GetString("familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Familias.
        /// </summary>
        internal static string familias {
            get {
                return ResourceManager.GetString("familias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Apertura.
        /// </summary>
        internal static string fechapecuenta {
            get {
                return ResourceManager.GetString("fechapecuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Fin .
        /// </summary>
        internal static string fecha_fin {
            get {
                return ResourceManager.GetString("fecha_fin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha Inicio.
        /// </summary>
        internal static string fecha_ini {
            get {
                return ResourceManager.GetString("fecha_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de Cierre.
        /// </summary>
        internal static string fechcierrcuenta {
            get {
                return ResourceManager.GetString("fechcierrcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ficha de Proveedores.
        /// </summary>
        internal static string ficha_proveedor {
            get {
                return ResourceManager.GetString("ficha_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de Contrato.
        /// </summary>
        internal static string fin_cont {
            get {
                return ResourceManager.GetString("fin_cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frecuencia de  Pago.
        /// </summary>
        internal static string fre_pago {
            get {
                return ResourceManager.GetString("fre_pago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerente de Cuentas.
        /// </summary>
        internal static string gerenteCuentas {
            get {
                return ResourceManager.GetString("gerenteCuentas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestor de Cuenta.
        /// </summary>
        internal static string gestcuenta {
            get {
                return ResourceManager.GetString("gestcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupos de tiendas.
        /// </summary>
        internal static string grupos_tiendas {
            get {
                return ResourceManager.GetString("grupos_tiendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string guardar {
            get {
                return ResourceManager.GetString("guardar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histórico.
        /// </summary>
        internal static string historico {
            get {
                return ResourceManager.GetString("historico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string hora {
            get {
                return ResourceManager.GetString("hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario.
        /// </summary>
        internal static string horario {
            get {
                return ResourceManager.GetString("horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horarios.
        /// </summary>
        internal static string horarios {
            get {
                return ResourceManager.GetString("horarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horario de precios.
        /// </summary>
        internal static string horario_precios {
            get {
                return ResourceManager.GetString("horario_precios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        internal static string idioma {
            get {
                return ResourceManager.GetString("idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma por defecto.
        /// </summary>
        internal static string idioma_x_def {
            get {
                return ResourceManager.GetString("idioma_x_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de Tienda.
        /// </summary>
        internal static string id_tienda {
            get {
                return ResourceManager.GetString("id_tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impuesto.
        /// </summary>
        internal static string imp {
            get {
                return ResourceManager.GetString("imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprimir.
        /// </summary>
        internal static string imprimir {
            get {
                return ResourceManager.GetString("imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string impuesto {
            get {
                return ResourceManager.GetString("impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        internal static string inactivo {
            get {
                return ResourceManager.GetString("inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incremento de tiempo.
        /// </summary>
        internal static string incre_tiempo {
            get {
                return ResourceManager.GetString("incre_tiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de Clientes.
        /// </summary>
        internal static string infClientes {
            get {
                return ResourceManager.GetString("infClientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Apellido.
        /// </summary>
        internal static string ingresar_ape {
            get {
                return ResourceManager.GetString("ingresar_ape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar código.
        /// </summary>
        internal static string ingresar_cod {
            get {
                return ResourceManager.GetString("ingresar_cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Cuidad.
        /// </summary>
        internal static string ingresar_cuidad {
            get {
                return ResourceManager.GetString("ingresar_cuidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Descripción.
        /// </summary>
        internal static string ingresar_desc {
            get {
                return ResourceManager.GetString("ingresar_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Dirección.
        /// </summary>
        internal static string ingresar_direc {
            get {
                return ResourceManager.GetString("ingresar_direc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Correo Electrónico.
        /// </summary>
        internal static string ingresar_email {
            get {
                return ResourceManager.GetString("ingresar_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Nombre de Empresa.
        /// </summary>
        internal static string ingresar_empresa {
            get {
                return ResourceManager.GetString("ingresar_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Estado.
        /// </summary>
        internal static string ingresar_est {
            get {
                return ResourceManager.GetString("ingresar_est", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Número de Fax.
        /// </summary>
        internal static string ingresar_fax {
            get {
                return ResourceManager.GetString("ingresar_fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Fecha.
        /// </summary>
        internal static string ingresar_fecha {
            get {
                return ResourceManager.GetString("ingresar_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Impuesto.
        /// </summary>
        internal static string ingresar_imp {
            get {
                return ResourceManager.GetString("ingresar_imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Inactivo.
        /// </summary>
        internal static string ingresar_inactivo {
            get {
                return ResourceManager.GetString("ingresar_inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese el Límite de Crédito.
        /// </summary>
        internal static string ingresar_limcredito {
            get {
                return ResourceManager.GetString("ingresar_limcredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar mensaje....
        /// </summary>
        internal static string ingresar_msj {
            get {
                return ResourceManager.GetString("ingresar_msj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar nombre.
        /// </summary>
        internal static string ingresar_nom {
            get {
                return ResourceManager.GetString("ingresar_nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Número de Cuenta.
        /// </summary>
        internal static string ingresar_numcuenta {
            get {
                return ResourceManager.GetString("ingresar_numcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Pago Mínimo.
        /// </summary>
        internal static string ingresar_pagoMinimo {
            get {
                return ResourceManager.GetString("ingresar_pagoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar País.
        /// </summary>
        internal static string ingresar_pais {
            get {
                return ResourceManager.GetString("ingresar_pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Periodo de Gracia.
        /// </summary>
        internal static string ingresar_periodoGracia {
            get {
                return ResourceManager.GetString("ingresar_periodoGracia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Número de Teléfono.
        /// </summary>
        internal static string ingresar_tel {
            get {
                return ResourceManager.GetString("ingresar_tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar el Texto Adicional.
        /// </summary>
        internal static string ingresar_text {
            get {
                return ResourceManager.GetString("ingresar_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Tipo de Fecha de Vencimiento.
        /// </summary>
        internal static string ingresar_tipoFechaVecimento {
            get {
                return ResourceManager.GetString("ingresar_tipoFechaVecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Título.
        /// </summary>
        internal static string ingresar_titulo {
            get {
                return ResourceManager.GetString("ingresar_titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar Código Zip.
        /// </summary>
        internal static string ingresar_zip {
            get {
                return ResourceManager.GetString("ingresar_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar el ID del Impuesto.
        /// </summary>
        internal static string ingrese_taxidnum {
            get {
                return ResourceManager.GetString("ingrese_taxidnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio.
        /// </summary>
        internal static string inicio {
            get {
                return ResourceManager.GetString("inicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de Contrato.
        /// </summary>
        internal static string ini_cont {
            get {
                return ResourceManager.GetString("ini_cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventario.
        /// </summary>
        internal static string inventario {
            get {
                return ResourceManager.GetString("inventario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isla.
        /// </summary>
        internal static string isla {
            get {
                return ResourceManager.GetString("isla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVA.
        /// </summary>
        internal static string IVA {
            get {
                return ResourceManager.GetString("IVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jueves.
        /// </summary>
        internal static string jueves {
            get {
                return ResourceManager.GetString("jueves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel de Precio.
        /// </summary>
        internal static string levelprice {
            get {
                return ResourceManager.GetString("levelprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de Crédito.
        /// </summary>
        internal static string limcredcuenta {
            get {
                return ResourceManager.GetString("limcredcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de Crédito.
        /// </summary>
        internal static string limCredito {
            get {
                return ResourceManager.GetString("limCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Límite de edad (Años).
        /// </summary>
        internal static string limite_edad {
            get {
                return ResourceManager.GetString("limite_edad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes.
        /// </summary>
        internal static string lunes {
            get {
                return ResourceManager.GetString("lunes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Artículos.
        /// </summary>
        internal static string mant_arts {
            get {
                return ResourceManager.GetString("mant_arts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Cabeceras.
        /// </summary>
        internal static string mant_cabeceras {
            get {
                return ResourceManager.GetString("mant_cabeceras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de categorías.
        /// </summary>
        internal static string mant_categs {
            get {
                return ResourceManager.GetString("mant_categs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de departamentos.
        /// </summary>
        internal static string mant_departs {
            get {
                return ResourceManager.GetString("mant_departs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Descuentos.
        /// </summary>
        internal static string mant_descuentos {
            get {
                return ResourceManager.GetString("mant_descuentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Espacios Fríos.
        /// </summary>
        internal static string mant_espacios_frios {
            get {
                return ResourceManager.GetString("mant_espacios_frios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Familias.
        /// </summary>
        internal static string mant_familias {
            get {
                return ResourceManager.GetString("mant_familias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Horarios.
        /// </summary>
        internal static string mant_horario {
            get {
                return ResourceManager.GetString("mant_horario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Islas y Side Kick.
        /// </summary>
        internal static string mant_isla_side {
            get {
                return ResourceManager.GetString("mant_isla-side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Mensajes de Artículos.
        /// </summary>
        internal static string mant_msjArts {
            get {
                return ResourceManager.GetString("mant_msjArts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Segmentos.
        /// </summary>
        internal static string mant_segs {
            get {
                return ResourceManager.GetString("mant_segs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mantenimiento de Subcategorías.
        /// </summary>
        internal static string mant_subcats {
            get {
                return ResourceManager.GetString("mant_subcats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martes.
        /// </summary>
        internal static string martes {
            get {
                return ResourceManager.GetString("martes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Método de Aplicacion.
        /// </summary>
        internal static string metAplicacion {
            get {
                return ResourceManager.GetString("metAplicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métodos de envío.
        /// </summary>
        internal static string met_envio {
            get {
                return ResourceManager.GetString("met_envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miércoles.
        /// </summary>
        internal static string miercoles {
            get {
                return ResourceManager.GetString("miercoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutos.
        /// </summary>
        internal static string mins {
            get {
                return ResourceManager.GetString("mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneda CxC.
        /// </summary>
        internal static string money {
            get {
                return ResourceManager.GetString("money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto.
        /// </summary>
        internal static string monto {
            get {
                return ResourceManager.GetString("monto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monto Total.
        /// </summary>
        internal static string monto_total {
            get {
                return ResourceManager.GetString("monto_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje.
        /// </summary>
        internal static string msj {
            get {
                return ResourceManager.GetString("msj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensajes de artículos.
        /// </summary>
        internal static string msj_articulos {
            get {
                return ResourceManager.GetString("msj_articulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negociación .
        /// </summary>
        internal static string negociacion {
            get {
                return ResourceManager.GetString("negociacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel A.
        /// </summary>
        internal static string nivel_a {
            get {
                return ResourceManager.GetString("nivel_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel B.
        /// </summary>
        internal static string nivel_b {
            get {
                return ResourceManager.GetString("nivel_b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nivel C.
        /// </summary>
        internal static string nivel_c {
            get {
                return ResourceManager.GetString("nivel_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        internal static string nomCliente {
            get {
                return ResourceManager.GetString("nomCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Departamento.
        /// </summary>
        internal static string nom_depart {
            get {
                return ResourceManager.GetString("nom_depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre del Proveedor.
        /// </summary>
        internal static string nom_proveedor {
            get {
                return ResourceManager.GetString("nom_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notas.
        /// </summary>
        internal static string notes {
            get {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO DEFINIDO.
        /// </summary>
        internal static string no_def {
            get {
                return ResourceManager.GetString("no_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        internal static string nuevo {
            get {
                return ResourceManager.GetString("nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Cuenta.
        /// </summary>
        internal static string numCuenta {
            get {
                return ResourceManager.GetString("numCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Fax.
        /// </summary>
        internal static string numFax {
            get {
                return ResourceManager.GetString("numFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número Móvil.
        /// </summary>
        internal static string nummovil {
            get {
                return ResourceManager.GetString("nummovil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Serie.
        /// </summary>
        internal static string numSerie {
            get {
                return ResourceManager.GetString("numSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrato.
        /// </summary>
        internal static string num_contrato {
            get {
                return ResourceManager.GetString("num_contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Parrillas.
        /// </summary>
        internal static string num_parrillas {
            get {
                return ResourceManager.GetString("num_parrillas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operaciones Central.
        /// </summary>
        internal static string operaciones {
            get {
                return ResourceManager.GetString("operaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Página de Inicio.
        /// </summary>
        internal static string paginicio {
            get {
                return ResourceManager.GetString("paginicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pago Mínimo.
        /// </summary>
        internal static string pagoMinimo {
            get {
                return ResourceManager.GetString("pagoMinimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Términos de Pago.
        /// </summary>
        internal static string paymentTerms {
            get {
                return ResourceManager.GetString("paymentTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período de Gracia.
        /// </summary>
        internal static string periodoGracia {
            get {
                return ResourceManager.GetString("periodoGracia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personas y Seguridad.
        /// </summary>
        internal static string pers_seguridad {
            get {
                return ResourceManager.GetString("pers_seguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primer Nombre.
        /// </summary>
        internal static string pnombre {
            get {
                return ResourceManager.GetString("pnombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porcentaje de Descuento.
        /// </summary>
        internal static string porcent_desc {
            get {
                return ResourceManager.GetString("porcent_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio de descuento.
        /// </summary>
        internal static string prec_desc {
            get {
                return ResourceManager.GetString("prec_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precio Reg..
        /// </summary>
        internal static string prec_reg {
            get {
                return ResourceManager.GetString("prec_reg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefijo.
        /// </summary>
        internal static string pref {
            get {
                return ResourceManager.GetString("pref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Productos.
        /// </summary>
        internal static string prod {
            get {
                return ResourceManager.GetString("prod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string proveedor {
            get {
                return ResourceManager.GetString("proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedores.
        /// </summary>
        internal static string proveedores {
            get {
                return ResourceManager.GetString("proveedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerta.
        /// </summary>
        internal static string puerta {
            get {
                return ResourceManager.GetString("puerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representantes de Ventas.
        /// </summary>
        internal static string rep_ventas {
            get {
                return ResourceManager.GetString("rep_ventas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revisión de Límite de Crédito.
        /// </summary>
        internal static string revLimCre {
            get {
                return ResourceManager.GetString("revLimCre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol.
        /// </summary>
        internal static string rolcuenta {
            get {
                return ResourceManager.GetString("rolcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        internal static string sabado {
            get {
                return ResourceManager.GetString("sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo Vencido.
        /// </summary>
        internal static string salvencuenta {
            get {
                return ResourceManager.GetString("salvencuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmento.
        /// </summary>
        internal static string segmento {
            get {
                return ResourceManager.GetString("segmento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmentos.
        /// </summary>
        internal static string segmentos {
            get {
                return ResourceManager.GetString("segmentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Gerente de Cuentas.
        /// </summary>
        internal static string select_accountmanager {
            get {
                return ResourceManager.GetString("select_accountmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Cargo Financiero.
        /// </summary>
        internal static string select_financecharge {
            get {
                return ResourceManager.GetString("select_financecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione el Número de Serie.
        /// </summary>
        internal static string select_numseries {
            get {
                return ResourceManager.GetString("select_numseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un Término de Pago.
        /// </summary>
        internal static string select_payterm {
            get {
                return ResourceManager.GetString("select_payterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione Tipo de Instrución.
        /// </summary>
        internal static string select_statementtype {
            get {
                return ResourceManager.GetString("select_statementtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una categoría.
        /// </summary>
        internal static string selec_categ {
            get {
                return ResourceManager.GetString("selec_categ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione un departamento.
        /// </summary>
        internal static string selec_depart {
            get {
                return ResourceManager.GetString("selec_depart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar Proveedor.
        /// </summary>
        internal static string selec_prov {
            get {
                return ResourceManager.GetString("selec_prov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Kick.
        /// </summary>
        internal static string side {
            get {
                return ResourceManager.GetString("side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo nombre.
        /// </summary>
        internal static string snombre {
            get {
                return ResourceManager.GetString("snombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategoría.
        /// </summary>
        internal static string subCategoria {
            get {
                return ResourceManager.GetString("subCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategorías.
        /// </summary>
        internal static string subCategorias {
            get {
                return ResourceManager.GetString("subCategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sufijo.
        /// </summary>
        internal static string sufcuenta {
            get {
                return ResourceManager.GetString("sufcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID de Contribuyente.
        /// </summary>
        internal static string taxidnum {
            get {
                return ResourceManager.GetString("taxidnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string tel {
            get {
                return ResourceManager.GetString("tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Término de Pago.
        /// </summary>
        internal static string termPago {
            get {
                return ResourceManager.GetString("termPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tienda.
        /// </summary>
        internal static string tienda {
            get {
                return ResourceManager.GetString("tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiendas.
        /// </summary>
        internal static string tiendas {
            get {
                return ResourceManager.GetString("tiendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Instrucíon.
        /// </summary>
        internal static string tipInstruccion {
            get {
                return ResourceManager.GetString("tipInstruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string tipo {
            get {
                return ResourceManager.GetString("tipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Fecha de Vencimiento.
        /// </summary>
        internal static string tipoFechaVecimento {
            get {
                return ResourceManager.GetString("tipoFechaVecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Descuento.
        /// </summary>
        internal static string tipo_descuento {
            get {
                return ResourceManager.GetString("tipo_descuento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezcle y Combine: Precio Unitario.
        /// </summary>
        internal static string tipo_descuento_1 {
            get {
                return ResourceManager.GetString("tipo_descuento_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compre X y lleve Y por Z: Precio Unitario.
        /// </summary>
        internal static string tipo_descuento_2 {
            get {
                return ResourceManager.GetString("tipo_descuento_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mezcle y Combine: Porcentaje de Descuento.
        /// </summary>
        internal static string tipo_descuento_3 {
            get {
                return ResourceManager.GetString("tipo_descuento_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compre X y lleve Y por Z: Porcentaje de Descuento.
        /// </summary>
        internal static string tipo_descuento_4 {
            get {
                return ResourceManager.GetString("tipo_descuento_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string titulo {
            get {
                return ResourceManager.GetString("titulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportistas de envío.
        /// </summary>
        internal static string trans_envio {
            get {
                return ResourceManager.GetString("trans_envio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación .
        /// </summary>
        internal static string ubicacion {
            get {
                return ResourceManager.GetString("ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Última Actualización.
        /// </summary>
        internal static string ultactcuenta {
            get {
                return ResourceManager.GetString("ultactcuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último Estado.
        /// </summary>
        internal static string ultEst {
            get {
                return ResourceManager.GetString("ultEst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidades de Medida.
        /// </summary>
        internal static string unids_medidas {
            get {
                return ResourceManager.GetString("unids_medidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios Central.
        /// </summary>
        internal static string usu_central {
            get {
                return ResourceManager.GetString("usu_central", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuarios de Tienda.
        /// </summary>
        internal static string usu_tienda {
            get {
                return ResourceManager.GetString("usu_tienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificación Límite de Crédito.
        /// </summary>
        internal static string verificacionLimCredito {
            get {
                return ResourceManager.GetString("verificacionLimCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia del Contrato .
        /// </summary>
        internal static string vic_contrato {
            get {
                return ResourceManager.GetString("vic_contrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viernes.
        /// </summary>
        internal static string viernes {
            get {
                return ResourceManager.GetString("viernes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigencia.
        /// </summary>
        internal static string vigencia {
            get {
                return ResourceManager.GetString("vigencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código Postal.
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
