#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security.DataAccess.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AVS_SECURITY")]
	public partial class SecurityDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public SecurityDBDataContext() : 
				base(global::Security.DataAccess.ConnectionString.Get(), mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SecurityDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_USER_VALIDATE")]
		public ISingleResult<SC_USER_VALIDATEResult> SC_USER_VALIDATE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACCOUNT", DbType="VarChar(50)")] string aCCOUNT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AUTOID", DbType="Int")] System.Nullable<int> aUTOID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SYSTEMID", DbType="Int")] System.Nullable<int> sYSTEMID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCCOUNT, aUTOID, sYSTEMID);
			return ((ISingleResult<SC_USER_VALIDATEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_USER_VALIDATE_SESSION")]
		public ISingleResult<SC_USER_VALIDATE_SESSIONResult> SC_USER_VALIDATE_SESSION([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AUTOID", DbType="Int")] System.Nullable<int> aUTOID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SYSTEMID", DbType="Int")] System.Nullable<int> sYSTEMID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, aUTOID, sYSTEMID);
			return ((ISingleResult<SC_USER_VALIDATE_SESSIONResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_SYSTEM_VALIDATE")]
		public ISingleResult<SC_SYSTEM_VALIDATEResult> SC_SYSTEM_VALIDATE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SYSTEM_CODE", DbType="VarChar(30)")] string sYSTEM_CODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID, sYSTEM_CODE);
			return ((ISingleResult<SC_SYSTEM_VALIDATEResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_MODULE_VALIDATE_GET")]
		public ISingleResult<SC_MODULE_VALIDATE_GETResult> SC_MODULE_VALIDATE_GET([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SYSTEM_CODE", DbType="VarChar(30)")] string sYSTEM_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sYSTEM_CODE, uSER_ID);
			return ((ISingleResult<SC_MODULE_VALIDATE_GETResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_VIEW_VALIDATE_GET")]
		public ISingleResult<SC_VIEW_VALIDATE_GETResult> SC_VIEW_VALIDATE_GET([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SYSTEM_CODE", DbType="VarChar(30)")] string sYSTEM_CODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSER_ID, sYSTEM_CODE);
			return ((ISingleResult<SC_VIEW_VALIDATE_GETResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SC_DATAACCESS_VALIDATE")]
		public ISingleResult<SC_DATAACCESS_VALIDATEResult> SC_DATAACCESS_VALIDATE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATA_CODE", DbType="VarChar(30)")] string dATA_CODE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USER_ID", DbType="Int")] System.Nullable<int> uSER_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SYSTEM_CODE", DbType="VarChar(30)")] string sYSTEM_CODE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dATA_CODE, uSER_ID, sYSTEM_CODE);
			return ((ISingleResult<SC_DATAACCESS_VALIDATEResult>)(result.ReturnValue));
		}
	}
	
	public partial class SC_USER_VALIDATEResult
	{
		
		private int _ID;
		
		private int _AutoID;
		
		private int _SystemID;
		
		private string _Account;
		
		private string _Name;
		
		private bool _EnCloseSession;
		
		private bool _Enable;
		
		public SC_USER_VALIDATEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoID", DbType="Int NOT NULL")]
		public int AutoID
		{
			get
			{
				return this._AutoID;
			}
			set
			{
				if ((this._AutoID != value))
				{
					this._AutoID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemID", DbType="Int NOT NULL")]
		public int SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				if ((this._SystemID != value))
				{
					this._SystemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this._Account = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnCloseSession", DbType="Bit NOT NULL")]
		public bool EnCloseSession
		{
			get
			{
				return this._EnCloseSession;
			}
			set
			{
				if ((this._EnCloseSession != value))
				{
					this._EnCloseSession = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enable", DbType="Bit NOT NULL")]
		public bool Enable
		{
			get
			{
				return this._Enable;
			}
			set
			{
				if ((this._Enable != value))
				{
					this._Enable = value;
				}
			}
		}
	}
	
	public partial class SC_USER_VALIDATE_SESSIONResult
	{
		
		private int _ID;
		
		public SC_USER_VALIDATE_SESSIONResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	public partial class SC_SYSTEM_VALIDATEResult
	{
		
		private System.Nullable<int> _RESULT;
		
		private System.Nullable<bool> _RESULT_STATUS;
		
		public SC_SYSTEM_VALIDATEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT", DbType="Int")]
		public System.Nullable<int> RESULT
		{
			get
			{
				return this._RESULT;
			}
			set
			{
				if ((this._RESULT != value))
				{
					this._RESULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT_STATUS", DbType="Bit")]
		public System.Nullable<bool> RESULT_STATUS
		{
			get
			{
				return this._RESULT_STATUS;
			}
			set
			{
				if ((this._RESULT_STATUS != value))
				{
					this._RESULT_STATUS = value;
				}
			}
		}
	}
	
	public partial class SC_MODULE_VALIDATE_GETResult
	{
		
		private int _ID;
		
		private int _SystemID;
		
		private string _Code;
		
		private string _Name;
		
		private bool _Enable;
		
		public SC_MODULE_VALIDATE_GETResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemID", DbType="Int NOT NULL")]
		public int SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				if ((this._SystemID != value))
				{
					this._SystemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enable", DbType="Bit NOT NULL")]
		public bool Enable
		{
			get
			{
				return this._Enable;
			}
			set
			{
				if ((this._Enable != value))
				{
					this._Enable = value;
				}
			}
		}
	}
	
	public partial class SC_VIEW_VALIDATE_GETResult
	{
		
		private int _ID;
		
		private int _MuduleID;
		
		private string _Code;
		
		private string _Name;
		
		private bool _Enable;
		
		public SC_VIEW_VALIDATE_GETResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MuduleID", DbType="Int NOT NULL")]
		public int MuduleID
		{
			get
			{
				return this._MuduleID;
			}
			set
			{
				if ((this._MuduleID != value))
				{
					this._MuduleID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(80) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enable", DbType="Bit NOT NULL")]
		public bool Enable
		{
			get
			{
				return this._Enable;
			}
			set
			{
				if ((this._Enable != value))
				{
					this._Enable = value;
				}
			}
		}
	}
	
	public partial class SC_DATAACCESS_VALIDATEResult
	{
		
		private int _DataID;
		
		private string _DataCode;
		
		private string _DataDescription;
		
		private string _DataTableName;
		
		private string _DataTablePKName;
		
		private int _DataSystemID;
		
		private bool _DataEnable;
		
		private int _DataAccessID;
		
		private string _DataAccessDescription;
		
		private bool _DataAccessEnAll;
		
		private string _DataAccessDataIDs;
		
		private System.Nullable<bool> _DataAccessEnable;
		
		public SC_DATAACCESS_VALIDATEResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataID", DbType="Int NOT NULL")]
		public int DataID
		{
			get
			{
				return this._DataID;
			}
			set
			{
				if ((this._DataID != value))
				{
					this._DataID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataCode", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string DataCode
		{
			get
			{
				return this._DataCode;
			}
			set
			{
				if ((this._DataCode != value))
				{
					this._DataCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataDescription", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string DataDescription
		{
			get
			{
				return this._DataDescription;
			}
			set
			{
				if ((this._DataDescription != value))
				{
					this._DataDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataTableName", DbType="VarChar(150)")]
		public string DataTableName
		{
			get
			{
				return this._DataTableName;
			}
			set
			{
				if ((this._DataTableName != value))
				{
					this._DataTableName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataTablePKName", DbType="VarChar(50)")]
		public string DataTablePKName
		{
			get
			{
				return this._DataTablePKName;
			}
			set
			{
				if ((this._DataTablePKName != value))
				{
					this._DataTablePKName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSystemID", DbType="Int NOT NULL")]
		public int DataSystemID
		{
			get
			{
				return this._DataSystemID;
			}
			set
			{
				if ((this._DataSystemID != value))
				{
					this._DataSystemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEnable", DbType="Bit NOT NULL")]
		public bool DataEnable
		{
			get
			{
				return this._DataEnable;
			}
			set
			{
				if ((this._DataEnable != value))
				{
					this._DataEnable = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAccessID", DbType="Int NOT NULL")]
		public int DataAccessID
		{
			get
			{
				return this._DataAccessID;
			}
			set
			{
				if ((this._DataAccessID != value))
				{
					this._DataAccessID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAccessDescription", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string DataAccessDescription
		{
			get
			{
				return this._DataAccessDescription;
			}
			set
			{
				if ((this._DataAccessDescription != value))
				{
					this._DataAccessDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAccessEnAll", DbType="Bit NOT NULL")]
		public bool DataAccessEnAll
		{
			get
			{
				return this._DataAccessEnAll;
			}
			set
			{
				if ((this._DataAccessEnAll != value))
				{
					this._DataAccessEnAll = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAccessDataIDs", DbType="VarChar(1000)")]
		public string DataAccessDataIDs
		{
			get
			{
				return this._DataAccessDataIDs;
			}
			set
			{
				if ((this._DataAccessDataIDs != value))
				{
					this._DataAccessDataIDs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataAccessEnable", DbType="Bit")]
		public System.Nullable<bool> DataAccessEnable
		{
			get
			{
				return this._DataAccessEnable;
			}
			set
			{
				if ((this._DataAccessEnable != value))
				{
					this._DataAccessEnable = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
