//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralAdmin.wcfAnalitica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfAnalitica.IAnaliticaService")]
    public interface IAnaliticaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetAllGraphics", ReplyAction="http://tempuri.org/IAnaliticaService/GetAllGraphicsResponse")]
        Analitic.Entities.EN_Graphics[] GetAllGraphics(string storeID, string codSucursal, string usersID, string busqueda, string fromDate, string toDate, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetAllGraphics", ReplyAction="http://tempuri.org/IAnaliticaService/GetAllGraphicsResponse")]
        System.Threading.Tasks.Task<Analitic.Entities.EN_Graphics[]> GetAllGraphicsAsync(string storeID, string codSucursal, string usersID, string busqueda, string fromDate, string toDate, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetAllAsientos", ReplyAction="http://tempuri.org/IAnaliticaService/GetAllAsientosResponse")]
        Analitic.Entities.EN_Asientos[] GetAllAsientos(string storesID, string hqUsersID, string searchValue, string estadoAsiento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetAllAsientos", ReplyAction="http://tempuri.org/IAnaliticaService/GetAllAsientosResponse")]
        System.Threading.Tasks.Task<Analitic.Entities.EN_Asientos[]> GetAllAsientosAsync(string storesID, string hqUsersID, string searchValue, string estadoAsiento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetCountRecordAsientosERP", ReplyAction="http://tempuri.org/IAnaliticaService/GetCountRecordAsientosERPResponse")]
        System.Collections.Generic.Dictionary<string, int> GetCountRecordAsientosERP(string storesID, string hqUsersID, string searchValue, string estadoAsiento, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetCountRecordAsientosERP", ReplyAction="http://tempuri.org/IAnaliticaService/GetCountRecordAsientosERPResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCountRecordAsientosERPAsync(string storesID, string hqUsersID, string searchValue, string estadoAsiento, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetAllDocsERP", ReplyAction="http://tempuri.org/IAnaliticaService/GetAllDocsERPResponse")]
        Analitic.Entities.EN_DocumentosERP[] GetAllDocsERP(string storesID, string hqUsersID, string searchValue, string tipoDocumento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetAllDocsERP", ReplyAction="http://tempuri.org/IAnaliticaService/GetAllDocsERPResponse")]
        System.Threading.Tasks.Task<Analitic.Entities.EN_DocumentosERP[]> GetAllDocsERPAsync(string storesID, string hqUsersID, string searchValue, string tipoDocumento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetCountRecordDocsERP", ReplyAction="http://tempuri.org/IAnaliticaService/GetCountRecordDocsERPResponse")]
        System.Collections.Generic.Dictionary<string, int> GetCountRecordDocsERP(string storesID, string hqUsersID, string searchValue, string tipoDocumento, string fromDate, string toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnaliticaService/GetCountRecordDocsERP", ReplyAction="http://tempuri.org/IAnaliticaService/GetCountRecordDocsERPResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCountRecordDocsERPAsync(string storesID, string hqUsersID, string searchValue, string tipoDocumento, string fromDate, string toDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnaliticaServiceChannel : CentralAdmin.wcfAnalitica.IAnaliticaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnaliticaServiceClient : System.ServiceModel.ClientBase<CentralAdmin.wcfAnalitica.IAnaliticaService>, CentralAdmin.wcfAnalitica.IAnaliticaService {
        
        public AnaliticaServiceClient() {
        }
        
        public AnaliticaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnaliticaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnaliticaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnaliticaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Analitic.Entities.EN_Graphics[] GetAllGraphics(string storeID, string codSucursal, string usersID, string busqueda, string fromDate, string toDate, string tipo) {
            return base.Channel.GetAllGraphics(storeID, codSucursal, usersID, busqueda, fromDate, toDate, tipo);
        }
        
        public System.Threading.Tasks.Task<Analitic.Entities.EN_Graphics[]> GetAllGraphicsAsync(string storeID, string codSucursal, string usersID, string busqueda, string fromDate, string toDate, string tipo) {
            return base.Channel.GetAllGraphicsAsync(storeID, codSucursal, usersID, busqueda, fromDate, toDate, tipo);
        }
        
        public Analitic.Entities.EN_Asientos[] GetAllAsientos(string storesID, string hqUsersID, string searchValue, string estadoAsiento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate) {
            return base.Channel.GetAllAsientos(storesID, hqUsersID, searchValue, estadoAsiento, orderColumn, orderDirection, skip, take, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<Analitic.Entities.EN_Asientos[]> GetAllAsientosAsync(string storesID, string hqUsersID, string searchValue, string estadoAsiento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate) {
            return base.Channel.GetAllAsientosAsync(storesID, hqUsersID, searchValue, estadoAsiento, orderColumn, orderDirection, skip, take, fromDate, toDate);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetCountRecordAsientosERP(string storesID, string hqUsersID, string searchValue, string estadoAsiento, string fromDate, string toDate) {
            return base.Channel.GetCountRecordAsientosERP(storesID, hqUsersID, searchValue, estadoAsiento, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCountRecordAsientosERPAsync(string storesID, string hqUsersID, string searchValue, string estadoAsiento, string fromDate, string toDate) {
            return base.Channel.GetCountRecordAsientosERPAsync(storesID, hqUsersID, searchValue, estadoAsiento, fromDate, toDate);
        }
        
        public Analitic.Entities.EN_DocumentosERP[] GetAllDocsERP(string storesID, string hqUsersID, string searchValue, string tipoDocumento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate) {
            return base.Channel.GetAllDocsERP(storesID, hqUsersID, searchValue, tipoDocumento, orderColumn, orderDirection, skip, take, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<Analitic.Entities.EN_DocumentosERP[]> GetAllDocsERPAsync(string storesID, string hqUsersID, string searchValue, string tipoDocumento, int orderColumn, string orderDirection, int skip, int take, string fromDate, string toDate) {
            return base.Channel.GetAllDocsERPAsync(storesID, hqUsersID, searchValue, tipoDocumento, orderColumn, orderDirection, skip, take, fromDate, toDate);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetCountRecordDocsERP(string storesID, string hqUsersID, string searchValue, string tipoDocumento, string fromDate, string toDate) {
            return base.Channel.GetCountRecordDocsERP(storesID, hqUsersID, searchValue, tipoDocumento, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetCountRecordDocsERPAsync(string storesID, string hqUsersID, string searchValue, string tipoDocumento, string fromDate, string toDate) {
            return base.Channel.GetCountRecordDocsERPAsync(storesID, hqUsersID, searchValue, tipoDocumento, fromDate, toDate);
        }
    }
}
