#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Analitic.DataAccess.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AVS_ANALITICA")]
	public partial class AnaliticDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public AnaliticDBDataContext() : 
				base(global::Analitic.DataAccess.ConnectionString.Get(), mappingSource)
		{
			OnCreated();
		}
		
		public AnaliticDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnaliticDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnaliticDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AnaliticDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UEP_ANALITICA_GRAPHICS_GETALL")]
		public ISingleResult<UEP_ANALITICA_GRAPHICS_GETALLResult> UEP_ANALITICA_GRAPHICS_GETALL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STORE_ID", DbType="VarChar(2)")] string sTORE_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_SUCURSAL", DbType="VarChar(3)")] string cOD_SUCURSAL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERS_ID", DbType="VarChar(1000)")] string uSERS_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchValue", DbType="NVarChar(100)")] string searchValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="VarChar(30)")] string fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="VarChar(30)")] string tODATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO", DbType="VarChar(30)")] string tIPO)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTORE_ID, cOD_SUCURSAL, uSERS_ID, searchValue, fROMDATE, tODATE, tIPO);
			return ((ISingleResult<UEP_ANALITICA_GRAPHICS_GETALLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UEP_ASIENTOS_ERP_GETALL")]
		public ISingleResult<UEP_ASIENTOS_ERP_GETALLResult> UEP_ASIENTOS_ERP_GETALL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STORES", DbType="VarChar(1000)")] string sTORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERS_ID", DbType="VarChar(1000)")] string uSERS_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchValue", DbType="NVarChar(100)")] string searchValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoAsiento", DbType="NVarChar(10)")] string estadoAsiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderColumn", DbType="Int")] System.Nullable<int> orderColumn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderDirection", DbType="NVarChar(4)")] string orderDirection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Skip", DbType="Int")] System.Nullable<int> skip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Take", DbType="Int")] System.Nullable<int> take, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="VarChar(30)")] string fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="VarChar(30)")] string tODATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTORES, uSERS_ID, searchValue, estadoAsiento, orderColumn, orderDirection, skip, take, fROMDATE, tODATE);
			return ((ISingleResult<UEP_ASIENTOS_ERP_GETALLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UEP_ASIENTOS_ERP_GET_COUNT_RECORDS")]
		public ISingleResult<UEP_ASIENTOS_ERP_GET_COUNT_RECORDSResult> UEP_ASIENTOS_ERP_GET_COUNT_RECORDS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STORES", DbType="VarChar(1000)")] string sTORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERS_ID", DbType="VarChar(1000)")] string uSERS_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchValue", DbType="NVarChar(100)")] string searchValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EstadoAsiento", DbType="NVarChar(10)")] string estadoAsiento, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="VarChar(30)")] string fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="VarChar(30)")] string tODATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTORES, uSERS_ID, searchValue, estadoAsiento, fROMDATE, tODATE);
			return ((ISingleResult<UEP_ASIENTOS_ERP_GET_COUNT_RECORDSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UEP_DOCUMENTOSERP_GET_COUNT_RECORDS")]
		public ISingleResult<UEP_DOCUMENTOSERP_GET_COUNT_RECORDSResult> UEP_DOCUMENTOSERP_GET_COUNT_RECORDS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STORES", DbType="VarChar(1000)")] string sTORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERS_ID", DbType="VarChar(1000)")] string uSERS_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchValue", DbType="NVarChar(100)")] string searchValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_DOCUMENTO", DbType="VarChar(30)")] string tIPO_DOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="VarChar(30)")] string fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="VarChar(30)")] string tODATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTORES, uSERS_ID, searchValue, tIPO_DOCUMENTO, fROMDATE, tODATE);
			return ((ISingleResult<UEP_DOCUMENTOSERP_GET_COUNT_RECORDSResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UEP_DOCUMENTOSERP_GETALL")]
		public ISingleResult<UEP_DOCUMENTOSERP_GETALLResult> UEP_DOCUMENTOSERP_GETALL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STORES", DbType="VarChar(1000)")] string sTORES, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERS_ID", DbType="VarChar(1000)")] string uSERS_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchValue", DbType="NVarChar(100)")] string searchValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TIPO_DOCUMENTO", DbType="VarChar(30)")] string tIPO_DOCUMENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderColumn", DbType="Int")] System.Nullable<int> orderColumn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderDirection", DbType="NVarChar(4)")] string orderDirection, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Skip", DbType="Int")] System.Nullable<int> skip, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Take", DbType="Int")] System.Nullable<int> take, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FROMDATE", DbType="VarChar(30)")] string fROMDATE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TODATE", DbType="VarChar(30)")] string tODATE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTORES, uSERS_ID, searchValue, tIPO_DOCUMENTO, orderColumn, orderDirection, skip, take, fROMDATE, tODATE);
			return ((ISingleResult<UEP_DOCUMENTOSERP_GETALLResult>)(result.ReturnValue));
		}
	}
	
	public partial class UEP_ANALITICA_GRAPHICS_GETALLResult
	{
		
		private string _Meses;
		
		private System.Nullable<int> _Num_Mes;
		
		private string _Primer_Dia;
		
		private System.Nullable<System.DateTime> _Ultimo_Dia;
		
		private System.Nullable<int> _Doc_Aceptados;
		
		private System.Nullable<int> _Doc_Rechazados;
		
		private int _Tot_Doc_Aceptados;
		
		private int _Tot_Doc_Rechazados;
		
		public UEP_ANALITICA_GRAPHICS_GETALLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Meses", DbType="NVarChar(30)")]
		public string Meses
		{
			get
			{
				return this._Meses;
			}
			set
			{
				if ((this._Meses != value))
				{
					this._Meses = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Num_Mes", DbType="Int")]
		public System.Nullable<int> Num_Mes
		{
			get
			{
				return this._Num_Mes;
			}
			set
			{
				if ((this._Num_Mes != value))
				{
					this._Num_Mes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primer_Dia", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string Primer_Dia
		{
			get
			{
				return this._Primer_Dia;
			}
			set
			{
				if ((this._Primer_Dia != value))
				{
					this._Primer_Dia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ultimo_Dia", DbType="Date")]
		public System.Nullable<System.DateTime> Ultimo_Dia
		{
			get
			{
				return this._Ultimo_Dia;
			}
			set
			{
				if ((this._Ultimo_Dia != value))
				{
					this._Ultimo_Dia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Aceptados", DbType="Int")]
		public System.Nullable<int> Doc_Aceptados
		{
			get
			{
				return this._Doc_Aceptados;
			}
			set
			{
				if ((this._Doc_Aceptados != value))
				{
					this._Doc_Aceptados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doc_Rechazados", DbType="Int")]
		public System.Nullable<int> Doc_Rechazados
		{
			get
			{
				return this._Doc_Rechazados;
			}
			set
			{
				if ((this._Doc_Rechazados != value))
				{
					this._Doc_Rechazados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Doc_Aceptados", DbType="Int NOT NULL")]
		public int Tot_Doc_Aceptados
		{
			get
			{
				return this._Tot_Doc_Aceptados;
			}
			set
			{
				if ((this._Tot_Doc_Aceptados != value))
				{
					this._Tot_Doc_Aceptados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tot_Doc_Rechazados", DbType="Int NOT NULL")]
		public int Tot_Doc_Rechazados
		{
			get
			{
				return this._Tot_Doc_Rechazados;
			}
			set
			{
				if ((this._Tot_Doc_Rechazados != value))
				{
					this._Tot_Doc_Rechazados = value;
				}
			}
		}
	}
	
	public partial class UEP_ASIENTOS_ERP_GETALLResult
	{
		
		private int _ID;
		
		private int _Codigo_negocio;
		
		private string _Nombre_negocio;
		
		private string _Descripcion;
		
		private string _Referencia;
		
		private System.DateTime _Fecha_asiento;
		
		private System.Nullable<System.DateTime> _Fecha_Sync;
		
		private string _Detalle_Sync;
		
		private System.Nullable<int> _Estado_Sync;
		
		public UEP_ASIENTOS_ERP_GETALLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo_negocio", DbType="Int NOT NULL")]
		public int Codigo_negocio
		{
			get
			{
				return this._Codigo_negocio;
			}
			set
			{
				if ((this._Codigo_negocio != value))
				{
					this._Codigo_negocio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre_negocio", DbType="VarChar(50)")]
		public string Nombre_negocio
		{
			get
			{
				return this._Nombre_negocio;
			}
			set
			{
				if ((this._Nombre_negocio != value))
				{
					this._Nombre_negocio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(80)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Referencia", DbType="VarChar(50)")]
		public string Referencia
		{
			get
			{
				return this._Referencia;
			}
			set
			{
				if ((this._Referencia != value))
				{
					this._Referencia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_asiento", DbType="DateTime NOT NULL")]
		public System.DateTime Fecha_asiento
		{
			get
			{
				return this._Fecha_asiento;
			}
			set
			{
				if ((this._Fecha_asiento != value))
				{
					this._Fecha_asiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha_Sync", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha_Sync
		{
			get
			{
				return this._Fecha_Sync;
			}
			set
			{
				if ((this._Fecha_Sync != value))
				{
					this._Fecha_Sync = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detalle_Sync", DbType="VarChar(80)")]
		public string Detalle_Sync
		{
			get
			{
				return this._Detalle_Sync;
			}
			set
			{
				if ((this._Detalle_Sync != value))
				{
					this._Detalle_Sync = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado_Sync", DbType="Int")]
		public System.Nullable<int> Estado_Sync
		{
			get
			{
				return this._Estado_Sync;
			}
			set
			{
				if ((this._Estado_Sync != value))
				{
					this._Estado_Sync = value;
				}
			}
		}
	}
	
	public partial class UEP_ASIENTOS_ERP_GET_COUNT_RECORDSResult
	{
		
		private System.Nullable<int> _TOTAL_RECORDS;
		
		private System.Nullable<int> _TOTAL_FILTERED;
		
		public UEP_ASIENTOS_ERP_GET_COUNT_RECORDSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECORDS", DbType="Int")]
		public System.Nullable<int> TOTAL_RECORDS
		{
			get
			{
				return this._TOTAL_RECORDS;
			}
			set
			{
				if ((this._TOTAL_RECORDS != value))
				{
					this._TOTAL_RECORDS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_FILTERED", DbType="Int")]
		public System.Nullable<int> TOTAL_FILTERED
		{
			get
			{
				return this._TOTAL_FILTERED;
			}
			set
			{
				if ((this._TOTAL_FILTERED != value))
				{
					this._TOTAL_FILTERED = value;
				}
			}
		}
	}
	
	public partial class UEP_DOCUMENTOSERP_GET_COUNT_RECORDSResult
	{
		
		private System.Nullable<int> _TOTAL_RECORDS;
		
		private System.Nullable<int> _TOTAL_FILTERED;
		
		public UEP_DOCUMENTOSERP_GET_COUNT_RECORDSResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_RECORDS", DbType="Int")]
		public System.Nullable<int> TOTAL_RECORDS
		{
			get
			{
				return this._TOTAL_RECORDS;
			}
			set
			{
				if ((this._TOTAL_RECORDS != value))
				{
					this._TOTAL_RECORDS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_FILTERED", DbType="Int")]
		public System.Nullable<int> TOTAL_FILTERED
		{
			get
			{
				return this._TOTAL_FILTERED;
			}
			set
			{
				if ((this._TOTAL_FILTERED != value))
				{
					this._TOTAL_FILTERED = value;
				}
			}
		}
	}
	
	public partial class UEP_DOCUMENTOSERP_GETALLResult
	{
		
		private int _StoreID;
		
		private string _Name;
		
		private int _Documento;
		
		private System.DateTime _FechaEnvio;
		
		private string _RespuestaEnvio;
		
		private string _DetallesEnvio;
		
		private int _Status;
		
		private string _Tipo;
		
		public UEP_DOCUMENTOSERP_GETALLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreID", DbType="Int NOT NULL")]
		public int StoreID
		{
			get
			{
				return this._StoreID;
			}
			set
			{
				if ((this._StoreID != value))
				{
					this._StoreID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Documento", DbType="Int NOT NULL")]
		public int Documento
		{
			get
			{
				return this._Documento;
			}
			set
			{
				if ((this._Documento != value))
				{
					this._Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEnvio", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEnvio
		{
			get
			{
				return this._FechaEnvio;
			}
			set
			{
				if ((this._FechaEnvio != value))
				{
					this._FechaEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RespuestaEnvio", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string RespuestaEnvio
		{
			get
			{
				return this._RespuestaEnvio;
			}
			set
			{
				if ((this._RespuestaEnvio != value))
				{
					this._RespuestaEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetallesEnvio", DbType="NVarChar(800) NOT NULL", CanBeNull=false)]
		public string DetallesEnvio
		{
			get
			{
				return this._DetallesEnvio;
			}
			set
			{
				if ((this._DetallesEnvio != value))
				{
					this._DetallesEnvio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this._Tipo = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
