using System;

namespace UltraERP.BusinessEntities
{
    public class EN_Item
    {
        /**  NOTAS ***
		 * - Margenes de Utilidad Automáticos
		 * - Tipos de descuento automático
		 * {
		 *   - Inventario, modificables:
		 *      + Unidad de Medida
		 *      + Costo de Remplazo
		 *   - Automaticos:
		 *      + Disponible
		 * }
		 * */
        #region Fields
        private object dataVAR;
        private int iD;
        private int hQID;
        // De configuración Gereral
        private string itemLookupCode;
        private string description;
        private string extendedDescription;
        private string subDescription1;
        private string subDescription2;
        private string subDescription3;
        private short itemType;
        
        private decimal price;
        private decimal cost;
        // De ExtCentral_Item
        private string subDescription4;
        private string subDescription5;
        private string subDescription6;
        private string subDescription7;
        private string subDescription8;
        private string subDescription9;
        private string subDescription10;
        
        private int familyID;
        private int departmentID;
        private int categoryID;
        private int subCategoryID;
        private int segmentID;
        private int brandID;
        private int manufacturerID;
        private int purchaserID;
        private string familyCode;
        private string departmentCode;
        private string categoryCode;
        private string subCategoryCode;
        private string segmentCode;
        private string purchaserCode;
        private decimal utility;
        // De configuracion Precios
        private decimal priceA;
        private decimal priceB;
        private decimal priceC;
        private decimal mSRP;
        private decimal priceLowerBound;
        private decimal priceUpperBound;
        private int saleType;
        private decimal salePrice;
        private DateTime saleStartDate;
        private DateTime saleEndDate;
        private int saleScheduleID;
        private decimal buydownPrice;
        private float buydownQuantity;
        // De Compra
        private int supplierID;
        // De configuración Descuentos
        private int quantityDiscountID;
        // De configuracion Inventario
        private string unitOfMeasure;
        private decimal replacementCost;
        private float quantity;
        private DateTime lastReceived;
        private DateTime? lastUpdated;
        private DateTime lastSold;
        private decimal lastCost;
        private DateTime lastCounted;
        private DateTime dateCreated;
        //  Adicional
        private string familyName;
        private string departmentName;
        private string categoryName;
        private string subcategoryName;
        private string segmentName;
        private string brandDescription;
        private string manufacturerDescription;
        private string purchaserName;
        // De impuestos
        private int taxID;
        // Cosassss..... Saber.....
        private bool inactive;
        #region Atributos aún no necesarios
        /*
		private string binLocation;
		private decimal commissionAmount;
		private decimal commissionMaximum;
		private int commissionMode;
		private decimal commissionPercentProfit;
		private decimal commissionPercentSale;
		private bool foodStampable;
		private bool itemNotDiscountable;
		private string notes;
		private float quantityCommitted;
		private int serialNumberCount;
		private float tareWeightPercent;
		private int messageID;
		private int taxID;
		private float reorderPoint;
		private float restockLevel;
		private float tareWeight;
		
		private int tagAlongItem;
		private float tagAlongQuantity;
		private int parentItem;
		private float parentQuantity;
		private short barcodeFormat;
		private string pictureName;
		private bool quantityEntryNotAllowed;
		private bool priceMustBeEntered;
		private string blockSalesReason;
		private DateTime blockSalesAfterDate;
		private float weight;
		private bool taxable;
		private DateTime blockSalesBeforeDate;
		private bool webItem;
		private int blockSalesType;
		private int blockSalesScheduleID;
		private bool consignment;
		private bool doNotOrder;
		private string content;
		private string usuallyShip;
		private string numberFormat;
		private bool itemCannotBeRet;
		private bool itemCannotBeSold;
		private bool isAutogenerated;
		private bool isGlobalvoucher;
		private bool deleteZeroBalanceEntry;
		private int tenderID;
		*/
        #endregion
        #endregion

        #region Constructors
        public EN_Item() { }
        #endregion

        #region Properties
        public object DataVAR
        {
            get { return dataVAR; }
            set { dataVAR = value; }
        }
        public decimal BuydownPrice
        {
            get { return buydownPrice; }
            set { buydownPrice = value; }
        }
        public float BuydownQuantity
        {
            get { return buydownQuantity; }
            set { buydownQuantity = value; }
        }
        public string Description
        {
            get { return description; }
            set { description = value; }
        }
        public int HQID
        {
            get { return hQID; }
            set { hQID = value; }
        }
        public DateTime LastReceived
        {
            get { return lastReceived; }
            set { lastReceived = value; }
        }
        public DateTime? LastUpdated
        {
            get { return lastUpdated; }
            set { lastUpdated = value; }
        }
        public string LastUpdatedAux
        {
            get { return lastUpdated == null ? "" : ((DateTime)lastUpdated).ToString("dd/MM/yyyy"); }
        }
        public int ID
        {
            get { return iD; }
            set { iD = value; }
        }
        public string ItemLookupCode
        {
            get { return itemLookupCode; }
            set { itemLookupCode = value; }
        }

        public decimal Price
        {
            get { return price; }
            set { price = value; }
        }
        public decimal PriceA
        {
            get { return priceA; }
            set { priceA = value; }
        }
        public decimal PriceB
        {
            get { return priceB; }
            set { priceB = value; }
        }
        public decimal PriceC
        {
            get { return priceC; }
            set { priceC = value; }
        }
        public decimal SalePrice
        {
            get { return salePrice; }
            set { salePrice = value; }
        }
        public DateTime SaleStartDate
        {
            get { return saleStartDate; }
            set { saleStartDate = value; }
        }
        public DateTime SaleEndDate
        {
            get { return saleEndDate; }
            set { saleEndDate = value; }
        }
        public int QuantityDiscountID
        {
            get { return quantityDiscountID; }
            set { quantityDiscountID = value; }
        }
        public decimal PriceLowerBound
        {
            get { return priceLowerBound; }
            set { priceLowerBound = value; }
        }
        public decimal PriceUpperBound
        {
            get { return priceUpperBound; }
            set { priceUpperBound = value; }
        }
        public DateTime LastSold
        {
            get { return lastSold; }
            set { lastSold = value; }
        }
        public string LastSoldAux
        {
            get { return lastSold != null ? lastSold.ToString("dd/MM/yyyy") : ""; }
        }
        public string ExtendedDescription
        {
            get { return extendedDescription; }
            set { extendedDescription = value; }
        }
        public string SubDescription1
        {
            get { return subDescription1; }
            set { subDescription1 = value; }
        }
        public string SubDescription2
        {
            get { return subDescription2; }
            set { subDescription2 = value; }
        }
        public string SubDescription3
        {
            get { return subDescription3; }
            set { subDescription3 = value; }
        }
        public string SubDescription4
        {
            get { return subDescription4; }
            set { subDescription4 = value; }
        }
        public string SubDescription5
        {
            get { return subDescription5; }
            set { subDescription5 = value; }
        }
        public string SubDescription6
        {
            get { return subDescription6; }
            set { subDescription6 = value; }
        }
        public string SubDescription7
        {
            get { return subDescription7; }
            set { subDescription7 = value; }
        }
        public string SubDescription8
        {
            get { return subDescription8; }
            set { subDescription8 = value; }
        }
        public string SubDescription9
        {
            get { return subDescription9; }
            set { subDescription9 = value; }
        }
        public string SubDescription10
        {
            get { return subDescription10; }
            set { subDescription10 = value; }
        }

        public decimal Utility
        {
            get { return utility; }
            set { utility = value; }
        }
        public string UnitOfMeasure
        {
            get { return unitOfMeasure; }
            set { unitOfMeasure = value; }
        }
        public decimal LastCost
        {
            get { return lastCost; }
            set { lastCost = value; }
        }
        public decimal ReplacementCost
        {
            get { return replacementCost; }
            set { replacementCost = value; }
        }
        public int SaleScheduleID
        {
            get { return saleScheduleID; }
            set { saleScheduleID = value; }
        }
        public int SaleType
        {
            get { return saleType; }
            set { saleType = value; }
        }
        public bool Inactive
        {
            get { return inactive; }
            set { inactive = value; }
        }
        public DateTime LastCounted
        {
            get { return lastCounted; }
            set { lastCounted = value; }
        }
        public decimal MSRP
        {
            get { return mSRP; }
            set { mSRP = value; }
        }
        public DateTime DateCreated
        {
            get { return dateCreated; }
            set { dateCreated = value; }
        }
        public short ItemType
        {
            get { return itemType; }
            set { itemType = value; }
        }
        public decimal Cost
        {
            get { return cost; }
            set { cost = value; }
        }
        public float Quantity
        {
            get { return quantity; }
            set { quantity = value; }
        }

        public int FamilyID
        {
            get { return familyID; }
            set { familyID = value; }
        }
        public int DepartmentID
        {
            get { return departmentID; }
            set { departmentID = value; }
        }
        public int CategoryID
        {
            get { return categoryID; }
            set { categoryID = value; }
        }
        public int SubCategoryID
        {
            get { return subCategoryID; }
            set { subCategoryID = value; }
        }
        public int SegmentID
        {
            get { return segmentID; }
            set { segmentID = value; }
        }
        
        public string FamilyCode
        {
            get { return familyCode; }
            set { familyCode = value; }
        }
        public string DepartmentCode
        {
            get { return departmentCode; }
            set { departmentCode = value; }
        }
        public string CategoryCode
        {
            get { return categoryCode; }
            set { categoryCode = value; }
        }
        public string SubCategoryCode
        {
            get { return subCategoryCode; }
            set { subCategoryCode = value; }
        }
        public string SegmentCode
        {
            get { return segmentCode; }
            set { segmentCode = value; }
        }
        public int BrandID
        {
            get { return brandID; }
            set { brandID = value; }
        }
        public int ManufacturerID
        {
            get { return manufacturerID; }
            set { manufacturerID = value; }
        }
        public int PurchaserID
        {
            get { return purchaserID; }
            set { purchaserID = value; }
        }
        public string PurchaserCode
        {
            get { return purchaserCode; }
            set { purchaserCode = value; }
        }


        public string FamilyName
        {
            get { return familyName; }
            set { familyName = value; }
        }
        public string DepartmentName
        {
            get { return departmentName; }
            set { departmentName = value; }
        }
        public string CategoryName
        {
            get { return categoryName; }
            set { categoryName = value; }
        }
        public string SubCategoryName
        {
            get { return subcategoryName; }
            set { subcategoryName = value; }
        }
        public string SegmentName
        {
            get { return segmentName; }
            set { segmentName = value; }
        }
        public string BrandDescription
        {
            get { return brandDescription; }
            set { brandDescription = value; }
        }
        public string ManufacturerDescription
        {
            get { return manufacturerDescription; }
            set { manufacturerDescription = value; }
        }
        public string PurchaserName
        {
            get { return purchaserName; }
            set { purchaserName = value; }
        }

        public int TaxID
        {
            get { return taxID; }
            set { taxID = value; }
        }

        public int SupplierID
        {
            get { return supplierID; }
            set { supplierID = value; }
        }

        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public decimal SupplierCost { get; set; }
        public string SupplierCostStartDate { get; set; }
        public string QuantityDiscountName { get; set; }
        public decimal InvoiceDiscount { get; set; }
        public decimal CustomerDiscount { get; set; }

        public float TaxPercentage { get; set; }

        public string StoresSelected { get; set; }
        public string StoresNameSelected { get; set; }
        #region Propiedades aún no necesarias
        /*
        public string BinLocation
        {
            get { return binLocation; }
            set { binLocation = value; }
        }
		public decimal CommissionAmount
		{
			get { return commissionAmount; }
			set { commissionAmount = value; }
		}
		public decimal CommissionMaximum
		{
			get { return commissionMaximum; }
			set { commissionMaximum = value; }
		}
		public int CommissionMode
		{
			get { return commissionMode; }
			set { commissionMode = value; }
		}
		public decimal CommissionPercentProfit
		{
			get { return commissionPercentProfit; }
			set { commissionPercentProfit = value; }
		}
		public decimal CommissionPercentSale
		{
			get { return commissionPercentSale; }
			set { commissionPercentSale = value; }
		}
		public bool FoodStampable
		{
			get { return foodStampable; }
			set { foodStampable = value; }
		}
		public bool ItemNotDiscountable
		{
			get { return itemNotDiscountable; }
			set { itemNotDiscountable = value; }
		}
		public string Notes
		{
			get { return notes; }
			set { notes = value; }
		}
		public float QuantityCommitted
		{
			get { return quantityCommitted; }
			set { quantityCommitted = value; }
		}
		public int SerialNumberCount
		{
			get { return serialNumberCount; }
			set { serialNumberCount = value; }
		}
		public float TareWeightPercent
		{
			get { return tareWeightPercent; }
			set { tareWeightPercent = value; }
		}
		public int MessageID
		{
			get { return messageID; }
			set { messageID = value; }
		}
		public float ReorderPoint
		{
			get { return reorderPoint; }
			set { reorderPoint = value; }
		}
		public float RestockLevel
		{
			get { return restockLevel; }
			set { restockLevel = value; }
		}
		public float TareWeight
		{
			get { return tareWeight; }
			set { tareWeight = value; }
		}
		public int SupplierID
		{
			get { return supplierID; }
			set { supplierID = value; }
		}
		public int TagAlongItem
		{
			get { return tagAlongItem; }
			set { tagAlongItem = value; }
		}
		public float TagAlongQuantity
		{
			get { return tagAlongQuantity; }
			set { tagAlongQuantity = value; }
		}
		public int ParentItem
		{
			get { return parentItem; }
			set { parentItem = value; }
		}
		public float ParentQuantity
		{
			get { return parentQuantity; }
			set { parentQuantity = value; }
		}
		public short BarcodeFormat
		{
			get { return barcodeFormat; }
			set { barcodeFormat = value; }
		}
		public string PictureName
		{
			get { return pictureName; }
			set { pictureName = value; }
		}
		public bool QuantityEntryNotAllowed
		{
			get { return quantityEntryNotAllowed; }
			set { quantityEntryNotAllowed = value; }
		}
		public bool PriceMustBeEntered
		{
			get { return priceMustBeEntered; }
			set { priceMustBeEntered = value; }
		}
		public string BlockSalesReason
		{
			get { return blockSalesReason; }
			set { blockSalesReason = value; }
		}
		public DateTime BlockSalesAfterDate
		{
			get { return blockSalesAfterDate; }
			set { blockSalesAfterDate = value; }
		}
		public float Weight
		{
			get { return weight; }
			set { weight = value; }
		}
		public bool Taxable
		{
			get { return taxable; }
			set { taxable = value; }
		}
		public DateTime BlockSalesBeforeDate
		{
			get { return blockSalesBeforeDate; }
			set { blockSalesBeforeDate = value; }
		}
		public bool WebItem
		{
			get { return webItem; }
			set { webItem = value; }
		}
		public int BlockSalesType
		{
			get { return blockSalesType; }
			set { blockSalesType = value; }
		}
		public int BlockSalesScheduleID
		{
			get { return blockSalesScheduleID; }
			set { blockSalesScheduleID = value; }
		}
		public bool Consignment
		{
			get { return consignment; }
			set { consignment = value; }
		}
		public bool DoNotOrder
		{
			get { return doNotOrder; }
			set { doNotOrder = value; }
		}
		public string Content
		{
			get { return content; }
			set { content = value; }
		}
		public string UsuallyShip
		{
			get { return usuallyShip; }
			set { usuallyShip = value; }
		}
		public string NumberFormat
		{
			get { return numberFormat; }
			set { numberFormat = value; }
		}
		public bool ItemCannotBeRet
		{
			get { return itemCannotBeRet; }
			set { itemCannotBeRet = value; }
		}
		public bool ItemCannotBeSold
		{
			get { return itemCannotBeSold; }
			set { itemCannotBeSold = value; }
		}
		public bool IsAutogenerated
		{
			get { return isAutogenerated; }
			set { isAutogenerated = value; }
		}
		public bool IsGlobalvoucher
		{
			get { return isGlobalvoucher; }
			set { isGlobalvoucher = value; }
		}
		public bool DeleteZeroBalanceEntry
		{
			get { return deleteZeroBalanceEntry; }
			set { deleteZeroBalanceEntry = value; }
		}
		public int TenderID
		{
			get { return tenderID; }
			set { tenderID = value; }
		}
		*/
        #endregion
        #endregion
    }
}
