//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentralAdmin.wcfSC_Security {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcfSC_Security.ISecurityServices")]
    public interface ISecurityServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/User_ValidateUser", ReplyAction="http://tempuri.org/ISecurityServices/User_ValidateUserResponse")]
        System.ValueTuple<Security.EntitiesAVS.EN_SC_User, int, string> User_ValidateUser(string account, int autoID, int systemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/User_ValidateUserSession", ReplyAction="http://tempuri.org/ISecurityServices/User_ValidateUserSessionResponse")]
        bool User_ValidateUserSession(int iD, int autoID, int systemID);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/User_GetCompanies", ReplyAction="http://tempuri.org/ISecurityServices/User_GetCompaniesResponse")]
        Security.EntitiesAVS.EN_SC_Company[] User_GetCompanies(string account, int autoID, int systemID);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/User_ValidateUserCompany", ReplyAction="http://tempuri.org/ISecurityServices/User_ValidateUserCompanyResponse")]
        System.ValueTuple<Security.EntitiesAVS.EN_SC_User, int, string> User_ValidateUserCompany(string account, int autoID, int systemID, int idCompany);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/User_ValidateUserSessionCompany", ReplyAction="http://tempuri.org/ISecurityServices/User_ValidateUserSessionCompanyResponse")]
        bool User_ValidateUserSessionCompany(int iD, int autoID, int systemID, int idCompany);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/System_ValidateSystem", ReplyAction="http://tempuri.org/ISecurityServices/System_ValidateSystemResponse")]
        System.ValueTuple<Security.EntitiesAVS.SC_Enum.ESystemValidateStatus, bool> System_ValidateSystem(int userID, string systemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/Module_ValidateModules", ReplyAction="http://tempuri.org/ISecurityServices/Module_ValidateModulesResponse")]
        Security.EntitiesAVS.EN_SC_Module[] Module_ValidateModules(int userID, string systemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/View_ValidateViews", ReplyAction="http://tempuri.org/ISecurityServices/View_ValidateViewsResponse")]
        Security.EntitiesAVS.EN_SC_View[] View_ValidateViews(int userID, string systemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityServices/DataAccess_ValidateDataAccess", ReplyAction="http://tempuri.org/ISecurityServices/DataAccess_ValidateDataAccessResponse")]
        Security.EntitiesAVS.EN_SC_DataAccess[] DataAccess_ValidateDataAccess(int userID, string systemCode, string dataCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServicesChannel : CentralAdmin.wcfSC_Security.ISecurityServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServicesClient : System.ServiceModel.ClientBase<CentralAdmin.wcfSC_Security.ISecurityServices>, CentralAdmin.wcfSC_Security.ISecurityServices {
        
        public SecurityServicesClient() {
        }
        
        public SecurityServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<Security.EntitiesAVS.EN_SC_User, int, string> User_ValidateUser(string account, int autoID, int systemID) {
            return base.Channel.User_ValidateUser(account, autoID, systemID);
        }
        
        public bool User_ValidateUserSession(int iD, int autoID, int systemID) {
            return base.Channel.User_ValidateUserSession(iD, autoID, systemID);
        }

        public Security.EntitiesAVS.EN_SC_Company[] User_GetCompanies(string account, int autoID, int systemID) {
            return base.Channel.User_GetCompanies(account, autoID, systemID);
        }

        public System.ValueTuple<Security.EntitiesAVS.EN_SC_User, int, string> User_ValidateUserCompany(string account, int autoID, int systemID, int idCompany) {
            return base.Channel.User_ValidateUserCompany(account, autoID, systemID, idCompany);
        }

        public bool User_ValidateUserSessionCompany(int iD, int autoID, int systemID, int idCompany) {
            return base.Channel.User_ValidateUserSessionCompany(iD, autoID, systemID, idCompany);
        }
        
        public System.ValueTuple<Security.EntitiesAVS.SC_Enum.ESystemValidateStatus, bool> System_ValidateSystem(int userID, string systemCode) {
            return base.Channel.System_ValidateSystem(userID, systemCode);
        }
        
        public Security.EntitiesAVS.EN_SC_Module[] Module_ValidateModules(int userID, string systemCode) {
            return base.Channel.Module_ValidateModules(userID, systemCode);
        }
        
        public Security.EntitiesAVS.EN_SC_View[] View_ValidateViews(int userID, string systemCode) {
            return base.Channel.View_ValidateViews(userID, systemCode);
        }
        
        public Security.EntitiesAVS.EN_SC_DataAccess[] DataAccess_ValidateDataAccess(int userID, string systemCode, string dataCode) {
            return base.Channel.DataAccess_ValidateDataAccess(userID, systemCode, dataCode);
        }
    }
}
